theme: jekyll-theme-minimal
title: "DactyloLibre"
description: "This tiny software will help you to training your typing skills for free"
source: "https://github.com/spoutnik911/DactyloLibre-CsharpVersion"
